Vagrant.configure("2") do |config|

  config.vm.define "win10" do |win10|
    win10.vm.box = "StefanScherer/windows_10"

    win10.vm.provider :virtualbox do |v, override|
      v.gui = true
      v.memory = 2048
      v.customize ["modifyvm", :id, "--cpus", "1"]
      v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
      v.customize ["modifyvm", :id, "--vram", 32]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--audio", "none"]
      v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      v.customize ["modifyvm", :id, "--draganddrop", "hosttoguest"]
      v.customize ["modifyvm", :id, "--usb", "off"]
      # Huge performance gain here
      v.linked_clone = true if Vagrant::VERSION >= '1.8.0'
    end

    # https://technet.microsoft.com/en-us/library/dn798297(v=ws.11).aspx
    win10.vm.provider :hyperv do |v, override|
      # 4GB RAM
      v.memory = 2048
      # 2 CPUs
      v.cpus = 1
      # The time in seconds to wait for the virtual machine to report an IP address
      v.ip_address_timeout = 130
      # Use differencing disk instead of cloning whole VHD
      v.differencing_disk = true
      v.vm_integration_services = {
      guest_service_interface: true,
      heartbeat: true,
      key_value_pair_exchange: true,
      shutdown: true,
      time_synchronization: true,
      vss: true
      }
    end

    # timeout of waiting for image to stop running - may be a deprecated setting
    config.windows.halt_timeout = 60
    # https://github.com/hashicorp/vagrant/issues/6430
    config.winrm.retry_limit = 30
    config.winrm.retry_delay = 10
    # username/password for accessing the image
#        win10.winrm.username = "vagrant"
#        win10.winrm.password = "vagrant"
    # explicitly tell Vagrant the guest is Windows
    win10.vm.guest = :windows
    win10.vm.communicator = "winrm"


    # Share `packages` directory as `C:\packages`
    win10.vm.synced_folder "c:\\choco-resources\\packages", "/packages"

    # Port forward WinRM / RDP
    # Vagrant 1.9.3 - if you run into Errno::EADDRNOTAVAIL (https://github.com/mitchellh/vagrant/issues/8395),
    #  add host_ip: "127.0.0.1" for it to work
    win10.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true, host_ip: "127.0.0.1"
    win10.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true, host_ip: "127.0.0.1"
    # Port forward SSH (ssh is forwarded by default in most versions of Vagrant,
    # but be sure). This is not necessary if you are not using SSH, but it doesn't
    # hurt anything to have it
    win10.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", auto_correct: true, host_ip: "127.0.0.1"

    # Provisioners - http://docs.vagrantup.com/v2/provisioning/
    # In this specific vagrant usage, we are using the shell provisioner
    # http://docs.vagrantup.com/v2/provisioning/shell.html
    win10.vm.provision :shell, :path => "../scripts/ConfigureAutoLogin.ps1", privileged: false
    win10.vm.provision :shell, :path => "../scripts/PrepareWindows.ps1", privileged: false
  end
end