# Vagrant File (Vagrantfile)
# http://docs.vagrantup.com/v2/vagrantfile/index.html

Vagrant.require_version ">= 2.0.0"

require 'json'

if File.exists?(File.expand_path "./package.json")  
    packages = JSON.parse(File.read(File.expand_path "./package.json"))
      puts packages
end  

# Need the vagrant reload plugin to reboot the box
unless Vagrant.has_plugin?("vagrant-reload")
  raise 'vagrant-reload plugin is not installed! Please install it with: vagrant plugin install vagrant-reload'
end

# http://docs.vagrantup.com/v2/vagrantfile/machine_settings.html
Vagrant.configure("2") do |config|
  # This setting will download the atlas box at
  # https://atlas.hashicorp.com/ferventcoder/boxes/win2012r2-x64-nocm
  config.vm.box = "win10-ent-x64-trial"

  config.vm.provider :hyperv do |h|
    # 4GB RAM
    h.memory = 512
	  h.maxmemory = 4096
    # 2 CPUs
    h.cpus = 1
	# Integration Services
    h.vm_integration_services = {
      guest_service_interface: true,
      heartbeat: true,
      key_value_pair_exchange: true,
      shutdown: true,
      time_synchronization: true,
      vss: true
    }
    # Huge performance gain here
    h.differencing_disk = true
  end
  
  # timeout of waiting for image to stop running - may be a deprecated setting
  config.windows.halt_timeout = 20
  # username/password for accessing the image
  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"
  # explicitly tell Vagrant the guest is Windows
  config.vm.guest = :windows
  config.vm.communicator = "winrm"
  
  # Synced folders - http://docs.vagrantup.com/v2/synced-folders/
  # A synced folder is a fancy term for shared folders - it takes a folder on
  # the host and shares it with the guest (vagrant) image. The entire folder
  # where the Vagrantfile is located is always shared as `c:\vagrant` (the
  # naming of this directory being `vagrant` is just a coincedence).
  # Share `packages` directory as `C:\packages`
  # Turn off the default vagrant synced folder as they don't work
  config.vm.synced_folder ".", "/vagrant", disabled: true
  #config.vm.synced_folder "packages", "c:/packages", "type": "rsync", create: true
  #config.vm.synced_folder "temp", "/Users/vagrant/AppData/Local/Temp/chocolatey"
  # not recommended for sharing, it may have issues with `vagrant sandbox rollback`
  #config.vm.synced_folder "chocolatey", "/ProgramData/chocolatey"

  # Port forward WinRM / RDP
  config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true
  config.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true

end