# http://docs.vagrantup.com/v2/vagrantfile/machine_settings.html
Vagrant.configure("2") do |config|

    config.vm.define "rbuild" do |rbuild|
        #config.vm.box = "ferventcoder/win2012r2-x64-nocm"
        rbuild.vm.box = "devopsguys/Windows2012R2Eval"

        # http://docs.vagrantup.com/v2/providers/configuration.html
        # http://docs.vagrantup.com/v2/virtualbox/configuration.html
        rbuild.vm.provider :virtualbox do |v, override|
            v.gui = true
            v.memory = 4096
            v.customize ["modifyvm", :id, "--cpus", "2"]
            v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
            v.customize ["modifyvm", :id, "--vram", 32]
            v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            v.customize ["modifyvm", :id, "--audio", "none"]
            v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
            v.customize ["modifyvm", :id, "--draganddrop", "hosttoguest"]
            v.customize ["modifyvm", :id, "--usb", "off"]
            # Huge performance gain here
            v.linked_clone = true if Vagrant::VERSION >= '1.8.0'
        end

        # https://www.vagrantup.com/docs/hyperv/configuration.html
        # https://technet.microsoft.com/en-us/library/dn798297(v=ws.11).aspx
        rbuild.vm.provider :hyperv do |v, override|
            # 4GB RAM
            v.memory = 4096
            # 2 CPUs
            v.cpus = 2
            # The time in seconds to wait for the virtual machine to report an IP address
            v.ip_address_timeout = 130
            # Use differencing disk instead of cloning whole VHD
            v.differencing_disk = true
            v.vm_integration_services = {
            guest_service_interface: true,
            heartbeat: true,
            key_value_pair_exchange: true,
            shutdown: true,
            time_synchronization: true,
            vss: true
            }
        end

        # timeout of waiting for image to stop running - may be a deprecated setting
        rbuild.windows.halt_timeout = 20
        # username/password for accessing the image
        rbuild.winrm.username = "vagrant"
        rbuild.winrm.password = "vagrant"
        # explicitly tell Vagrant the guest is Windows
        rbuild.vm.guest = :windows
        rbuild.vm.communicator = "winrm"


        # Share `packages` directory as `C:\packages`
        rbuild.vm.synced_folder "c:\\choco-resources\\packages", "/packages"
        #rbuild.vm.synced_folder "temp", "/Users/vagrant/AppData/Local/Temp/chocolatey"
        # not recommended for sharing, it may have issues with `vagrant sandbox rollback`
        #rbuild.vm.synced_folder "chocolatey", "/ProgramData/chocolatey"

        # Port forward WinRM / RDP
        # Vagrant 1.9.3 - if you run into Errno::EADDRNOTAVAIL (https://github.com/mitchellh/vagrant/issues/8395),
        #  add host_ip: "127.0.0.1" for it to work
        rbuild.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true #, host_ip: "127.0.0.1"
        rbuild.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true #, host_ip: "127.0.0.1"
        # Port forward SSH (ssh is forwarded by default in most versions of Vagrant,
        # but be sure). This is not necessary if you are not using SSH, but it doesn't
        # hurt anything to have it
        rbuild.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", auto_correct: true #, host_ip: "127.0.0.1"

        # Provisioners - http://docs.vagrantup.com/v2/provisioning/
        # In this specific vagrant usage, we are using the shell provisioner
        # http://docs.vagrantup.com/v2/provisioning/shell.html
        rbuild.vm.provision :shell, :path => "../scripts/ConfigureAutoLogin.ps1", privileged: false
        rbuild.vm.provision :shell, :path => "../scripts/PrepareWindows.ps1", privileged: false
        rbuild.vm.provision :shell, :path => "../scripts/InstallNet4.ps1", privileged: false
        rbuild.vm.provision :shell, :path => "../scripts/InstallChocolatey.ps1", args: "-UseLocalSource", privileged: false
        rbuild.vm.provision :shell, :path => "../scripts/InstallBGInfo.ps1", privileged: false
        rbuild.vm.provision :shell, :path => "../scripts/NotifyGuiAppsOfEnvironmentChanges.ps1", privileged: false
        rbuild.vm.provision :shell, :path => "../scripts/InstallStandardApps.ps1", privileged: false
        pkgs = ['jdk8', 'ruby', 'nodejs.install']
        pkgs.each { |pkg|
            # when using a variable (pkg here) use an array with :args
            rbuild.vm.provision :shell, :path => "../scripts/InstallChocoApps.ps1", :args => [pkg], privileged: false
        }
    end
end