Vagrant.configure("2") do |config|

  config.vagrant.plugins = 'vagrant-reload'

  config.vm.define "jenkins" do |cfg|

    #
    # Variables
    #
    folder_syncs = [
      { local: '../../resources/packages',               remote: '/packages' },
      { local: '../../resources/licenses',               remote: '/licenses' },
      { local: '../../resources',                        remote: '/resources' },
      { local: 'jenkins-scripts',                        remote: '/scripts' },
      { local: '../../shell',                            remote: '/shell' },
      { local: '~/git/pauby/mine/presentations',         remote: '/presentations' },
      { local: '~/git/pauby/mine/private-presentations', remote: '/private-presentations' }
    ]

    #
    # Providers
    #
    cfg.vm.provider :virtualbox do |v, override|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.gui = true
      v.customize ["modifyvm", :id, "--cpus", "2"]
      # turn on nested virtualization
      v.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
      v.customize ["modifyvm", :id, "--vram", 128]
      v.customize ["modifyvm", :id, "--memory", "4096"]
      v.customize ["modifyvm", :id, "--audio", "none"]
      v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      v.customize ["modifyvm", :id, "--draganddrop", "hosttoguest"]
      v.customize ["modifyvm", :id, "--usb", "off"]
      v.linked_clone = true
    end

    config.vm.provider :hyperv do |v, override|
      override.vm.network "public_network", bridge: "Default Switch"
      v.enable_virtualization_extensions = true
      v.maxmemory = 4096
      v.cpus = 2
      v.ip_address_timeout = 130
      v.linked_clone = true
      v.vm_integration_services = {
        guest_service_interface: true,
        heartbeat: true,
        key_value_pair_exchange: true,
        shutdown: true,
        time_synchronization: true,
        vss: true
      }

      smbcreds_filename = 'vagrant-smb.txt'
      if File.exists?(smbcreds_filename)
        file_data = File.read(smbcreds_filename).split
        smbusername = file_data[0]
        smbpassword = file_data[1]

        folder_syncs.each do |folder|
          #print "Folder sync local: #{folder[:local]} | remote: #{folder[:remote]} | smb_username: #{folder[:smb_username]} | smb_password: #{folder[:smb_password]}"
          override.vm.synced_folder folder[:local], folder[:remote], smb_username: smbusername, smb_password: smbpassword
        end
      end

      override.vm.provision "Stop SMB Idle Disconnects", type: 'shell', run: 'once', privileged: true, inline: 'net config server /autodisconnect:-1'
    end

    #
    # Configuration
    #
    cfg.vm.box = "StefanScherer/windows_2016"
    cfg.vm.hostname = "jenkins"

    cfg.windows.graceful_halt_timeout = 120
    # https://github.com/hashicorp/vagrant/issues/6430
    cfg.winrm.retry_limit = 60
    cfg.winrm.retry_delay = 10

    cfg.winrm.username = "vagrant"
    cfg.winrm.password = "vagrant"
    cfg.vm.guest = :windows
    cfg.vm.communicator = "winrm"

    cfg.windows.set_work_network = true
    #cfg.vm.network :private_network, ip: "192.168.100.10"

    cfg.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true, host_ip: "127.0.0.1"
    cfg.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true, host_ip: "127.0.0.1"
    cfg.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", auto_correct: true, host_ip: "127.0.0.1"

    folder_syncs.each do |folder|
      #print "Folder sync local: #{folder[:local]} | remote: #{folder[:remote]} | smb_username: #{folder[:smb_username]} | smb_password: #{folder[:smb_password]}"
      cfg.vm.synced_folder folder[:local], folder[:remote]
    end

    cfg.vm.provision :shell, :path => "../../shell/ConfigureAutoLogin.ps1", privileged: false
    cfg.vm.provision :shell, :path => "../../shell/PrepareWindows.ps1", privileged: false
    cfg.vm.provision :shell, :path => "../../shell/SetRegion.ps1", args: "-Region 'UK'", privileged: false
    cfg.vm.provision :shell, :path => "../../shell/InstallChocolatey.ps1", args: "-UseLocalSource", run: "once", privileged: false
    cfg.vm.provision :shell, :path => "../../shell/DeployChocolateyLicense.ps1", args: "-LicenseType Bus", run: "once", privileged: true
    cfg.vm.provision :shell, :path => "../../shell/NotifyGuiAppsOfEnvironmentChanges.ps1", run: "once", privileged: false
    cfg.vm.provision :shell, :path => "../../shell/InstallVMGuestTools.ps1", run: "once", privileged: false
    # This is very distracting during presenting so commenting it out - don't delete so we know why it's not used
    #cfg.vm.provision :shell, :path => "../../shell/InstallBGInfo.ps1", privileged: false
    cfg.vm.provision :shell, :path => "../../shell/InstallChocoPackage.ps1", args: "-Name 'vscode, vscode-powershell, git, chromium, pester, psscriptanalyzer, zoomit, notepadplusplus'", run: "once", privileged: false
    cfg.vm.provision :shell, :path => "../../shell/InstallChocoPackage.ps1", args: "-Name 'vagrant' -Version '2.2.4'", run: "once", privileged: false
    #cfg.vm.provision :shell, :path => "../../shell/InstallChocoPackage.ps1", args: "-Name 'virtualbox' -Version '6.0.8'", run: "once", privileged: false
    cfg.vm.provision :shell, :path => "shell/ProvisionChocolateyServerForJenkins.ps1", run: "once", privileged: false
    cfg.vm.provision :shell, :path => "../../shell/ProvisionJenkins.ps1", args: "-ConfigurationPath 'c:\\vagrant\\shell\\jenkins-config.zip'", run: "once", privileged: true

    cfg.vm.provision "Install Hyper-V", type: "shell", run: "once", privileged: true, inline: "Install-WindowsFeature -Name Hyper-V -IncludeManagementTools"
    cfg.vm.provision "Disable Windows Firewall", type: "shell", run: "once", privileged: true, inline: "Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False"

    # reload machine to have the auto-login and bginfo kick in
    cfg.vm.provision :reload

    cfg.vm.provision "Setup Vagrant", type: "shell", run: "once", privileged: true, inline: <<-SHELL
      # Vagrant
      # install vagrant reload plugin
      vagrant plugin install vagrant-reload
      # add the chocolatey test environment box
      #vagrant box add c:\\resources\\vagrant-boxes\\ferventcoder-win2012r2-x64-nocm-virtualbox.box --name 'ferventcoder/win2012r2-x64-nocm'
      vagrant box add c:\\resources\\vagrant-boxes\\stefanscherer-windows_2016-hyperv.box --name 'stefanscherer/windows_2016'
    SHELL

    cfg.vm.provision "Add Desktop Presentation Shortcuts", type: "shell", run: "once", privileged: true, inline: <<-SHELL
      # Taken from https://stackoverflow.com/questions/28997799/how-to-create-a-run-as-administrator-shortcut-using-powershell
      $WshShell = New-Object -comObject WScript.Shell
      $Shortcut = $WshShell.CreateShortcut("$Home\\Desktop\\VS Code Presentation.lnk")
      $Shortcut.TargetPath = "C:\\Program Files\\Microsoft VS Code\\Code.exe"
      $Shortcut.Save()

      $bytes = [System.IO.File]::ReadAllBytes("$Home\\Desktop\\VS Code Presentation.lnk")
      $bytes[0x15] = $bytes[0x15] -bor 0x20 #set byte 21 (0x15) bit 6 (0x20) ON
      [System.IO.File]::WriteAllBytes("$Home\\Desktop\\VS Code Presentation.lnk", $bytes)

      #git clone https://github.com/pauby/presentations c:\\git-presentations --depth 1 -q
      Remove-Variable -Name 'Shortcut' -Force -ErrorAction SilentlyContinue
      $WshShell = New-Object -comObject WScript.Shell
      $Shortcut = $WshShell.CreateShortcut("$Home\\Desktop\\Open Jenkins.lnk")
      $Shortcut.TargetPath = "C:\\Program Files\\Internet Explorer\\iexplore.exe"
      $Shortcut.Arguments = "http://localhost:8080"
      $Shortcut.Save()
    SHELL

    cfg.vm.provision "Create Zoomit Startup Shortcut", type: "shell", run: "once", privileged: true, inline: <<-SHELL
      $WshShell = New-Object -comObject WScript.Shell
      $link = Join-Path -Path ([Environment]::GetFolderPath('Startup')) -ChildPath 'Zoomit.lnk'
      $Shortcut = $WshShell.CreateShortcut($link)
      $Shortcut.TargetPath = (Join-Path -Path $env:ChocolateyInstall -Childpath 'bin\\zoomit.exe')
      $Shortcut.Save()

      # Launch Zoomit
      & (Join-Path -Path $env:ChocolateyInstall -Childpath 'bin/zoomit.exe')
    SHELL

    cfg.vm.post_up_message = "Jenkins Username is admin. All done!"
  end


  config.vm.define "client" do |cfg|

    #
    # Variables
    #
    folder_syncs = [
      { local: '../../resources/packages',               remote: '/packages' },
      { local: '../../resources',                        remote: '/resources' },
      { local: '../../shell',                            remote: '/shell' }
    ]

    #
    # Providers
    #
    cfg.vm.provider :virtualbox do |v, override|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.gui = true
      v.customize ["modifyvm", :id, "--cpus", "1"]
      # turn on nested virtualization
      v.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
      v.customize ["modifyvm", :id, "--vram", 128]
      v.customize ["modifyvm", :id, "--memory", "2048"]
      v.customize ["modifyvm", :id, "--audio", "none"]
      v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      v.customize ["modifyvm", :id, "--draganddrop", "hosttoguest"]
      v.customize ["modifyvm", :id, "--usb", "off"]
      v.linked_clone = true
    end

    config.vm.provider :hyperv do |v, override|
      override.vm.network "public_network", bridge: "Default Switch"
      v.enable_virtualization_extensions = true
      v.maxmemory = 2048
      v.cpus = 1
      v.ip_address_timeout = 130
      v.linked_clone = true
      v.vm_integration_services = {
        guest_service_interface: true,
        heartbeat: true,
        key_value_pair_exchange: true,
        shutdown: true,
        time_synchronization: true,
        vss: true
      }

      smbcreds_filename = 'vagrant-smb.txt'
      if File.exists?(smbcreds_filename)
        file_data = File.read(smbcreds_filename).split
        smbusername = file_data[0]
        smbpassword = file_data[1]

        folder_syncs.each do |folder|
          #print "Folder sync local: #{folder[:local]} | remote: #{folder[:remote]} | smb_username: #{folder[:smb_username]} | smb_password: #{folder[:smb_password]}"
          override.vm.synced_folder folder[:local], folder[:remote], smb_username: smbusername, smb_password: smbpassword
        end
      end

      override.vm.provision "Stop SMB Idle Disconnects", type: 'shell', run: 'once', privileged: true, inline: 'net config server /autodisconnect:-1'
    end

    #
    # Configuration
    #
    cfg.vm.box = "StefanScherer/windows_2016"
    cfg.vm.hostname = "client"

    cfg.windows.graceful_halt_timeout = 120
    # https://github.com/hashicorp/vagrant/issues/6430
    cfg.winrm.retry_limit = 60
    cfg.winrm.retry_delay = 10

    cfg.winrm.username = "vagrant"
    cfg.winrm.password = "vagrant"
    cfg.vm.guest = :windows
    cfg.vm.communicator = "winrm"

    cfg.windows.set_work_network = true

    cfg.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true, host_ip: "127.0.0.1"
    cfg.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true, host_ip: "127.0.0.1"
    cfg.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", auto_correct: true, host_ip: "127.0.0.1"

    folder_syncs.each do |folder|
      #print "Folder sync local: #{folder[:local]} | remote: #{folder[:remote]} | smb_username: #{folder[:smb_username]} | smb_password: #{folder[:smb_password]}"
      cfg.vm.synced_folder folder[:local], folder[:remote]
    end

    cfg.vm.provision :shell, :path => "../../shell/ConfigureAutoLogin.ps1", privileged: false
    cfg.vm.provision :shell, :path => "../../shell/PrepareWindows.ps1", privileged: false
    cfg.vm.provision :shell, :path => "../../shell/SetRegion.ps1", args: "-Region 'UK'", privileged: false
    cfg.vm.provision :shell, :path => "../../shell/InstallChocolatey.ps1", args: "-UseLocalSource", run: "once", privileged: false
    cfg.vm.provision :shell, :path => "../../shell/NotifyGuiAppsOfEnvironmentChanges.ps1", run: "once", privileged: false
    cfg.vm.provision :shell, :path => "../../shell/InstallVMGuestTools.ps1", run: "once", privileged: false
    # This is very distracting during presenting so commenting it out - don't delete so we know why it's not used
    #cfg.vm.provision :shell, :path => "../../shell/InstallBGInfo.ps1", privileged: false
    cfg.vm.provision :shell, :path => "../../shell/InstallChocoPackage.ps1", args: "-Name 'zoomit, notepadplusplus'", run: "once", privileged: false

    # reload machine to have the auto-login and bginfo kick in

    cfg.vm.provision "Create Zoomit Startup Shortcut", type: "shell", run: "once", privileged: true, inline: <<-SHELL
      $WshShell = New-Object -comObject WScript.Shell
      $link = Join-Path -Path ([Environment]::GetFolderPath('Startup')) -ChildPath 'Zoomit.lnk'
      $Shortcut = $WshShell.CreateShortcut($link)
      $Shortcut.TargetPath = (Join-Path -Path $env:ChocolateyInstall -Childpath 'bin\\zoomit.exe')
      $Shortcut.Save()
    SHELL

    cfg.vm.provision "Install Hyper-V", type: "shell", run: "once", privileged: true, inline: "choco source add --name='prodrepo' --source='http://jenkins:81/chocolatey' --priority='2' --bypass-proxy --allow-self-service"

    cfg.vm.provision :reload

    cfg.vm.post_up_message = "Jenkins Username is admin. All done!"
  end
end