unless Vagrant.has_plugin?("vagrant-reload")
  raise 'vagrant-reload is not installed!'
end

Vagrant.configure("2") do |config|

  config.vm.define "win2016", autostart: false

  config.windows.halt_timeout = 60
  # https://github.com/hashicorp/vagrant/issues/6430
  config.winrm.retry_limit = 30
  config.winrm.retry_delay = 10

  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"
  config.vm.guest = :windows
  config.vm.communicator = "winrm"

  config.windows.set_work_network = true

  config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true, host_ip: "127.0.0.1"
  config.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true, host_ip: "127.0.0.1"
  config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", auto_correct: true, host_ip: "127.0.0.1"

  config.vm.synced_folder "auto-install", "/auto-install"
  config.vm.synced_folder "../packages", "/packages"
  config.vm.synced_folder "../licenses", "/licenses"
  config.vm.synced_folder "../scripts", "/scripts"

  config.vm.provision :shell, :path => "../scripts/ConfigureAutoLogin.ps1", privileged: false
  config.vm.provision :shell, :path => "../scripts/PrepareWindows.ps1", privileged: false
  config.vm.provision :shell, :path => "../scripts/InstallNet4.ps1", privileged: false
  config.vm.provision :shell, :path => "../scripts/InstallChocolatey.ps1", args: "-UseLocalSource", privileged: false
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    choco source add -n=auto-install -s"c:\\auto-install" --priority=5
  SHELL
  config.vm.provision :shell, :path => "../scripts/NotifyGuiAppsOfEnvironmentChanges.ps1", privileged: false
  config.vm.provision :shell, :path => "../scripts/InstallStandardApps.ps1", privileged: false
  config.vm.provision :shell, :path => "../scripts/InstallBGInfo.ps1", privileged: false

  # reload machine to have the auto-login and bginfo kick in
  config.vm.provision :reload

  config.vm.post_up_message = "All done!"

  config.vm.define "win2016" do |win2016|
    win2016.vm.box = "StefanScherer/windows_2016"

    win2016.vm.hostname = "win2016"

    win2016.vm.provider :virtualbox do |v, override|
      #override.vm.network :private_network, ip: "10.10.13.14"
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.gui = true
      v.customize ["modifyvm", :id, "--vram", 32]
      v.customize ["modifyvm", :id, "--memory", "1024"]
      v.customize ["modifyvm", :id, "--audio", "none"]
      v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      v.customize ["modifyvm", :id, "--draganddrop", "hosttoguest"]
      v.customize ["modifyvm", :id, "--usb", "off"]
      # linked clones for speed and size
      v.linked_clone = true if Vagrant::VERSION >= '1.8.0'
    end
  end

  config.vm.define "win10" do |win10|
    win10.vm.box = "StefanScherer/windows_10"

    # http://docs.vagrantup.com/v2/providers/configuration.html
    # http://docs.vagrantup.com/v2/virtualbox/configuration.html
    win10.vm.provider :virtualbox do |v, override|
        v.gui = true
        v.memory = 2048
        v.customize ["modifyvm", :id, "--cpus", "1"]
        v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
        v.customize ["modifyvm", :id, "--vram", 32]
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--audio", "none"]
        v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
        v.customize ["modifyvm", :id, "--draganddrop", "hosttoguest"]
        v.customize ["modifyvm", :id, "--usb", "off"]
        # Huge performance gain here
        v.linked_clone = true if Vagrant::VERSION >= '1.8.0'
    end

    # https://www.vagrantup.com/docs/hyperv/configuration.html
    # https://technet.microsoft.com/en-us/library/dn798297(v=ws.11).aspx
    win10.vm.provider :hyperv do |v, override|
        # 4GB RAM
        v.memory = 2048
        # 2 CPUs
        v.cpus = 1
        # The time in seconds to wait for the virtual machine to report an IP address
        v.ip_address_timeout = 130
        # Use differencing disk instead of cloning whole VHD
        v.differencing_disk = true
        v.vm_integration_services = {
        guest_service_interface: true,
        heartbeat: true,
        key_value_pair_exchange: true,
        shutdown: true,
        time_synchronization: true,
        vss: true
        }
    end

  win10.vm.provision "shell", privileged: false, inline: <<-SHELL
    #http://www.blackviper.com/service-configurations/black-vipers-windows-10-service-configurations/
    'ajrouter', 'alg', 'appmgmt', 'appxsvc', 'bthavctpsvc', 'bits', 'btagservice', 'bthserv',
      'bluetoothuserservice_*', 'peerdistsvc', 'captureservice_*', 'certpropsvc', 'nfsclnt',
      'diagtrack', 'IpxlatCfgSvc', 'iphlpsvc', 'SharedAccess', 'irmon', 'vmicvss', 'vmictimesync',
      'vmicrdv', 'vmicvmsession', 'vmicheartbeat', 'vmicshutdown', 'vmicguestinterface', 'vmickvpexchange',
      'HvHost', 'lfsvc', 'MapsBroker', 'dmwappushsvc', 'PhoneSvc', 'SEMgrSvc', 'WpcMonSvc', 'CscService',
      'NcdAutoSetup', 'Netlogon', 'NaturalAuthentication', 'SmsRouter', 'MSiSCSI', 'AppVClient', 'SNMPTRAP',
      'SCPolicySvc', 'ScDeviceEnum', 'SCardSvr', 'SensorService', 'SensrSvc', 'SensorDataService', 'RetailDemo',
      'icssvc', 'WMPNetworkSvc', 'wisvc', 'wcncsvc', 'FrameServer', 'WFDSConSvc', 'WebClient', 'TabletInputService',
      'XboxNetApiSvc', 'XblGameSave', 'XblAuthManager', 'xbgm', 'WwanSvc' | ForEach-Object {
        Stop-Service -PassThru | Set-Service -StartupType Disabled
      }
    SHELL

  end # win10
end