# check plugins
unless Vagrant.has_plugin?("vagrant-reload")
  raise 'vagrant-reload is not installed!'
end

# http://docs.vagrantup.com/v2/vagrantfile/machine_settings.html
Vagrant.configure("2") do |config|

    config.vm.define "bt01" do |bt01|
        bt01.vm.box = "ferventcoder/win2012r2-x64-nocm"
        #bt01.vm.box = "devopsguys/Windows2012R2Eval"

        # http://docs.vagrantup.com/v2/providers/configuration.html
        # http://docs.vagrantup.com/v2/virtualbox/configuration.html
        bt01.vm.provider :virtualbox do |v, override|
            override.vm.network :private_network, ip: "192.168.1.10"

            # Show the GUI
            v.gui = true
            # 2GB RAM
            v.customize ["modifyvm", :id, "--memory", "2048"]
            # 2 CPUs
            v.customize ["modifyvm", :id, "--cpus", "2"]
            # Video RAM is 40 MB
            v.customize ["modifyvm", :id, "--vram", 40]
            # For better DNS resolution
            v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            # No audo
            v.customize ["modifyvm", :id, "--audio", "none"]
            # Clipboard enabled
            v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
            v.customize ["modifyvm", :id, "--draganddrop", "hosttoguest"]
            # For performance
            v.customize ["modifyvm", :id, "--usb", "off"]
            # Huge performance gain here
            v.linked_clone = true if Vagrant::VERSION >= '1.8.0'
        end

        # https://www.vagrantup.com/docs/hyperv/configuration.html
        # https://technet.microsoft.com/en-us/library/dn798297(v=ws.11).aspx
        bt01.vm.provider :hyperv do |v, override|
            override.vm.network :private_network, ip: "192.168.1.10"

            # 4GB RAM
            v.memory = 4096
            # 2 CPUs
            v.cpus = 2
            # The time in seconds to wait for the virtual machine to report an IP address
            v.ip_address_timeout = 130
            # Use differencing disk instead of cloning whole VHD
            v.differencing_disk = true
            v.vm_integration_services = {
            guest_service_interface: true,
            heartbeat: true,
            key_value_pair_exchange: true,
            shutdown: true,
            time_synchronization: true,
            vss: true
            }
        end

        #bt01.vm.hostname = "bt01"      # dont care what the vm is called
        bt01.windows.set_work_network = true
        # timeout of waiting for image to stop running - may be a deprecated setting
        bt01.windows.halt_timeout = 20
        # username/password for accessing the image
        bt01.winrm.username = "vagrant"
        bt01.winrm.password = "vagrant"
        # explicitly tell Vagrant the guest is Windows
        bt01.vm.guest = :windows
        bt01.vm.communicator = "winrm"

        bt01.vm.synced_folder "../resources/packages", "/packages"
        bt01.vm.synced_folder "../resources", "/resources"

        # Port forward WinRM / RDP
        # Vagrant 1.9.3 - if you run into Errno::EADDRNOTAVAIL (https://github.com/mitchellh/vagrant/issues/8395),
        #  add host_ip: "127.0.0.1" for it to work
        bt01.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true
        bt01.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true
        bt01.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", auto_correct: true

        bt01.vm.provision :shell, :path => "../scripts/ConfigureAutoLogin.ps1", privileged: false
        bt01.vm.provision "reload"
        bt01.vm.provision :shell, :path => "../scripts/PrepareWindows.ps1", privileged: false
        bt01.vm.provision :shell, :path => "../scripts/InstallNet4.ps1", privileged: false
        bt01.vm.provision :shell, :path => "../scripts/InstallChocolatey.ps1", privileged: false
        bt01.vm.provision :shell, :path => "../scripts/InstallStandardApps.ps1", privileged: false
        bt01.vm.provision :shell, :path => "../scripts/NotifyGuiAppsOfEnvironmentChanges.ps1", privileged: false

        bt01.vm.provision "shell", privileged: false, inline: <<-SHELL
            choco upgrade boxstarter -y --no-progress
        SHELL
        bt01.vm.provision "reload"
    end
end