unless Vagrant.has_plugin?("vagrant-reload")
  raise 'vagrant-reload is not installed!'
end

Vagrant.configure("2") do |config|

  config.vm.define "win2016" do |config|
    config.vm.box = "StefanScherer/windows_2016"

    config.windows.halt_timeout = 60
    # https://github.com/hashicorp/vagrant/issues/6430
    config.winrm.retry_limit = 30
    config.winrm.retry_delay = 10

    config.winrm.username = "vagrant"
    config.winrm.password = "vagrant"
    config.vm.guest = :windows
    config.vm.communicator = "winrm"

    config.vm.hostname = "win2016"
    config.windows.set_work_network = true

    config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true, host_ip: "127.0.0.1"
    config.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true, host_ip: "127.0.0.1"
    config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", auto_correct: true, host_ip: "127.0.0.1"

    config.vm.synced_folder "~/git", "/git"
    config.vm.synced_folder "../packages", "/packages"
    config.vm.synced_folder "../licenses", "/licenses"
    config.vm.synced_folder "../scripts", "/scripts"

    config.vm.provider :virtualbox do |v, override|
      override.vm.network :private_network, ip: "10.10.13.14"
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.gui = true
      v.customize ["modifyvm", :id, "--vram", 70]
      v.customize ["modifyvm", :id, "--memory", "1024"]
      v.customize ["modifyvm", :id, "--audio", "none"]
      v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      v.customize ["modifyvm", :id, "--draganddrop", "hosttoguest"]
      v.customize ["modifyvm", :id, "--usb", "off"]
      # linked clones for speed and size
      v.linked_clone = true if Vagrant::VERSION >= '1.8.0'
    end

  config.vm.provision :shell, :path => "../scripts/ConfigureAutoLogin.ps1", privileged: false
  config.vm.provision :shell, :path => "../scripts/PrepareWindows.ps1", privileged: false
  config.vm.provision :shell, :path => "../scripts/InstallNet4.ps1", privileged: false
  config.vm.provision :shell, :path => "../scripts/InstallChocolatey.ps1", args: "-UseLocalSource", privileged: false
  config.vm.provision :shell, :path => "../scripts/InstallChocoPackage.ps1", args: "-Name vscode, git", privileged: false
  config.vm.provision :shell, :path => "../scripts/PreparePowerShellBuildEnvironment.ps1", privileged: false
  config.vm.provision :shell, :path => "../scripts/NotifyGuiAppsOfEnvironmentChanges.ps1", privileged: false
  config.vm.provision :shell, :path => "../scripts/InstallStandardApps.ps1", privileged: false
  config.vm.provision :shell, :path => "../scripts/InstallBGInfo.ps1", privileged: false

  # reload machine to have the auto-login and bginfo kick in
  config.vm.provision :reload

  config.vm.post_up_message = "All done!"

  end
end